// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package memorydb

import (
	"encoding/json"
	"time"
)

type ConversationHistory struct {
	ID        uint64
	MessageID string
	UserID    string
	SessionID string
	Role      string
	Content   string
	Metadata  json.RawMessage
	CreatedAt time.Time
}
