// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package memorydb

import (
	"context"
	"encoding/json"
	"time"
)

const deleteHistory = `-- name: DeleteHistory :exec
DELETE FROM conversation_history
WHERE user_id = ?
  AND session_id = ?
`

type DeleteHistoryParams struct {
	UserID    string
	SessionID string
}

func (q *Queries) DeleteHistory(ctx context.Context, arg DeleteHistoryParams) error {
	_, err := q.db.ExecContext(ctx, deleteHistory, arg.UserID, arg.SessionID)
	return err
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT
    id,
    message_id,
    user_id,
    session_id,
    role,
    content,
    metadata,
    created_at
FROM conversation_history
WHERE user_id = ?
  AND session_id = ?
  AND message_id = ?
`

type GetMessageByIDParams struct {
	UserID    string
	SessionID string
	MessageID string
}

func (q *Queries) GetMessageByID(ctx context.Context, arg GetMessageByIDParams) (ConversationHistory, error) {
	row := q.db.QueryRowContext(ctx, getMessageByID, arg.UserID, arg.SessionID, arg.MessageID)
	var i ConversationHistory
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.UserID,
		&i.SessionID,
		&i.Role,
		&i.Content,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const insertMessage = `-- name: InsertMessage :exec
INSERT INTO conversation_history (
    message_id,
    user_id,
    session_id,
    role,
    content,
    metadata,
    created_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertMessageParams struct {
	MessageID string
	UserID    string
	SessionID string
	Role      string
	Content   string
	Metadata  json.RawMessage
	CreatedAt time.Time
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) error {
	_, err := q.db.ExecContext(ctx, insertMessage,
		arg.MessageID,
		arg.UserID,
		arg.SessionID,
		arg.Role,
		arg.Content,
		arg.Metadata,
		arg.CreatedAt,
	)
	return err
}

const listHistory = `-- name: ListHistory :many
SELECT
    id,
    message_id,
    user_id,
    session_id,
    role,
    content,
    metadata,
    created_at
FROM conversation_history
WHERE user_id = ?
  AND session_id = ?
ORDER BY created_at ASC, id ASC
LIMIT ?
`

type ListHistoryParams struct {
	UserID    string
	SessionID string
	Limit     int32
}

func (q *Queries) ListHistory(ctx context.Context, arg ListHistoryParams) ([]ConversationHistory, error) {
	rows, err := q.db.QueryContext(ctx, listHistory, arg.UserID, arg.SessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConversationHistory
	for rows.Next() {
		var i ConversationHistory
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.UserID,
			&i.SessionID,
			&i.Role,
			&i.Content,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
