// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package memorydb

import (
	"context"
)

type Querier interface {
	DeleteHistory(ctx context.Context, arg DeleteHistoryParams) error
	GetMessageByID(ctx context.Context, arg GetMessageByIDParams) (ConversationHistory, error)
	InsertMessage(ctx context.Context, arg InsertMessageParams) error
	ListHistory(ctx context.Context, arg ListHistoryParams) ([]ConversationHistory, error)
}

var _ Querier = (*Queries)(nil)
